using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

/*
    Euler Problem 61

    Keith Fletcher
    Jul 2017

    This file is Unlicensed.
    See the foot of the file, or refer to <http://unlicense.org>
*/

namespace HisRoyalRedness.com
{
    [Solution("")]
    public class Problem61 : ProblemBase
    {
        /// <summary>
        /// http://projecteuler.net/index.php?section=problems&id=61
        /// 
        /// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers 
        /// are all figurate(polygonal) numbers and are generated by the following formulae:
        /// 
        ///     Triangle    P3,     n = n(n + 1) / 2 	  	1, 3, 6, 10, 15, ...
        ///     Square      P4,     n = n2 	  	            1, 4, 9, 16, 25, ...
        ///     Pentagonal  P5,     n = n(3n−1) / 2 	  	1, 5, 12, 22, 35, ...
        ///     Hexagonal   P6,     n = n(2n−1) 	  	    1, 6, 15, 28, 45, ...
        ///     Heptagonal  P7,     n = n(5n−3) / 2 	  	1, 7, 18, 34, 55, ...
        ///     Octagonal   P8,     n = n(3n−2) 	  	    1, 8, 21, 40, 65, ...
        ///     
        /// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting 
        /// properties.
        /// 
        /// The set is cyclic, in that the last two digits of each number is the first two 
        /// digits of the next number(including the last number with the first).
        /// 
        /// Each polygonal type: triangle(P3,127=8128), square(P4,91=8281), and 
        /// pentagonal(P5,44=2882), is represented by a different number in the set.
        /// 
        /// This is the only set of 4-digit numbers with this property.
        /// 
        /// Find the sum of the only ordered set of six cyclic 4-digit numbers for which each 
        /// polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, 
        /// is represented by a different number in the set.
        /// 
        /// Answer: 
        /// </summary>

        protected override string InternalSolve()
        {
            // 0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351, 378, 406, 435, 465, 496, 528, 561, 595, 630, 666...
            var t = TriangleNumber.Sequence(10).Take(10).ToList();

            return "";
        }
    }
}

/*
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
*/
