using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.Composition;
using System.Reflection;
using System.Numerics;

namespace fletcher.org
{
    [Export(typeof(IProblem))]
    [Solution("4613732")]
    class Problem002Generator : ProblemBase
    {
        /// <summary>
        /// http://projecteuler.net/index.php?section=problems&id=2
        ///
        /// Each new term in the Fibonacci sequence is generated by adding
        /// the previous two terms. By starting with 1 and 2, the first
        /// 10 terms will be:
        ///
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
        ///
        /// Find the sum of all the even-valued terms in the sequence which
        /// do not exceed four million.
        ///
        /// Answer: 4613732
        /// </summary>
        public Problem002Generator() { }


        protected override string InternalCalculateSolution()
        {
            // Not inclusive!
            return Fibonacci.Sequence
                .TakeWhile(fib => fib < 4000000)
                .Skip(2)
                .Where(num => num % 2 == 0)
                .Sum().ToString();
        }
    }
}
