using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.Composition;
using System.Numerics;
using System.Reflection;

namespace fletcher.org
{
    [Export(typeof(IProblem))]
    [Solution("5482660")]
    class Problem044Generator : ProblemBase
    {
        /// <summary>
        /// http://projecteuler.net/index.php?section=problems&id=44
        /// 
        /// Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. 
        /// The first ten pentagonal numbers are:
        /// 
        /// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
        /// 
        /// It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, 
        /// their difference, 70 − 22 = 48, is not pentagonal.
        /// 
        /// Find the pair of pentagonal numbers, P_j and P_k, for which 
        /// their sum and difference is pentagonal and D = |P_k − P_j| 
        /// is minimised; what is the value of D?
        /// 
        /// Answer: 5482660
        /// </summary>
        public Problem044Generator() { }

        protected override string InternalCalculateSolution()
        {
            var limit = 5000;
            var list = new List<ulong>(PentagonalNumbers.Sequence.Take(limit));
            var hash = new HashSet<ulong>(list);

            for (int j = 0; j < limit; ++j)
            {
                for (int k = j + 1; k < limit; ++k)
                {
                    if (!hash.Contains(list[k] + list[j]))
                        continue;
                    if (hash.Contains(list[k] - list[j]))
                    {
                        Console.WriteLine(
                            "j = {0},  k = {1}\np_j = {2}\np_k = {3}\n\nD = |p_j - p_k| = {4}",
                            j + 1, k + 1, list[j], list[k], list[k] - list[j]);
                        return (list[k] - list[j]).ToString();
                    }
                }
            }
            return "";
        }

        
    }
}
