using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.Composition;
using System.Numerics;
using System.Reflection;

namespace fletcher.org
{
    [Export(typeof(IProblem))]
    [Solution("1533776805")]
    class Problem045Generator : ProblemBase
    {
        /// <summary>
        /// http://projecteuler.net/index.php?section=problems&id=45
        /// 
        /// Triangle, pentagonal, and hexagonal numbers are 
        /// generated by the following formulae:
        /// 
        /// Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
        /// Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
        /// Hexagonal 	  	H_n=n(2n−1)   	    1, 6, 15, 28, 45, ...
        /// 
        /// It can be verified that T_285 = P_165 = H_143 = 40755.
        /// Find the next triangle number that is also pentagonal and hexagonal.
        /// 
        /// Answer: 1533776805
        /// </summary>
        public Problem045Generator() { }

        protected override string InternalCalculateSolution()
        {
            // FAST!!!!

            ulong i3 = 286;
            ulong i5 = 165;
            ulong i6 = 143;

            var num3 = TriangleNumbers.AtIndex(i3);
            var num5 = PentagonalNumbers.AtIndex(i5);
            var num6 = HexagonalNumbers.AtIndex(i6);
            
            while (true)
            {
                while (num5 < num6)
                    num5 = PentagonalNumbers.AtIndex(++i5);

                if (num5 > num6)
                {
                    num6 = HexagonalNumbers.AtIndex(++i6);
                    continue;
                }

                if (num3 < num6)
                    num3 = TriangleNumbers.AtIndex(++i3);

                if (num3 > num6)
                {
                    num6 = HexagonalNumbers.AtIndex(++i6);
                    continue;
                }

                return num6.ToString();
            }
        }
    }
}
